### PR TITLE
Added query string support

### PR DESCRIPTION
**Pull request by xlbruce**
Made a little modification to parse either query string parameters

### CODE REVIEW

**Comment by KRoLer** [comment]
Great idea. I'll suggest updating Readme file with an example of usage.

**Comment by tranhungt** [comment]
Looks great @xlbruce. Thanks for the suggestion @KRoLer.

**Comment by xlbruce** [comment]
I'm happy to see you like this. Now I'm very busy, but until weekend I'll update README file with an example :D

**Comment by tranhungt** [comment]
Sounds great! Thanks @xlbruce!

**Comment by xlbruce** [comment]
@tranhungt I updated README file and created a pull request (https://github.com/opentable/wiremock-body-transformer/pull/23)

**Pull request closed without merging**
